# Generated by Django 5.1.6 on 2025-02-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="name",
            field=models.CharField(max_length=30, verbose_name="NAME"),
        ),
    ]
